[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel"]

build-backend = 'setuptools.build_meta'

[tool.coverage.run]
omit = [
    "some/directory/*",
    "docs/assets/*.py"
]